name: dartoos
description: Dart object-oriented primitives
version: 0.0.1
homepage: https://dartoos.dev
repository: https://github.com/dartoos-dev/dartoos

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^1.7.2
  test: ^1.18.2
